agent {
  data_dir       = "/opt/spire/data/agent"
  trust_domain   = "recoverysky.org"
  server_address = "spire.rso"
  server_port    = 54345
  socket_path    = "/tmp/spire-agent/public/api.sock"
  log_level      = "DEBUG"
  trust_bundle_path = "/opt/spire/conf/agent/recoverysky-spiffe-bundle.pem"
}

plugins {
  KeyManager "disk" {
      plugin_data = {
          directory = "/opt/spire/data/agent"
      }
  }
  
  # Use x509pop for certificate-based attestation
  NodeAttestor "x509pop" {
      plugin_data {
          private_key_path = "/opt/spire/conf/agent/key.pem"
          certificate_path = "/opt/spire/conf/agent/svid.pem"
      }
  }
  
  # Unix workload attestor for processes inside containers
  WorkloadAttestor "unix" {
    plugin_data {
    }
  }
}
